# updated: 01.08.2025
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Dashboard"
subtitle: "Ungi"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon
columns: "auto"
header: false
footer: false #'<p>Created with <span class="has-text-danger"> ^}   ^o</span> with <a h>

defaults:
  layout: "columns"
  colorTheme: "auto"

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for >
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo. <br /> Find more information on <a href='htt>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Home Assistant"
    icon: "fa-solid fa-house-chimney-window"
    url: "https://home-assistant.io/"
    target: "_blank" # optional html a tag target attribute
  - name: "ESP Home"
    icon: "fa-solid fa-microchip"
    url: "https://esphome.io/"
    target: "_blank"
  # this will link to a second homer page that will load config from additional-page.ym>
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional>
services:
  - name: "Services"
    icon: "fas fa-server"
    items:
      - name: "FritzBox"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/avm-fritzbox.png"
        tag: "rooter"
        url: "http://192.168.1.1"
        target: "_blank"
      - name: "Proxmox"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/proxmox.png"
        tag: "Server"
        url: "https://192.168.1.10:8006"
        target: "_blank" # optional html a tag target attribute
      - name: "Dockge"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/dockge.png"
        tag: "container"
        url: "http://192.168.1.12:5001"
        target: "_blank"
      - name: "Cloudflare"  
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cloudflare.png"
        tag: "proxy"
        url: "https://dash.cloudflare.com/"
        target: "_blank"

  - name: "Smart Home"
    icon: "fa-solid fa-house"
    items:
      - name: "Home Assistant"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/home-assistant.png"
        #subtitle: "Another application"
        tag: "hassio"
        url: "http://192.168.1.30:8123"
        target: "_blank"
      - name: "Stromzaehler ESP"
        logo: "https://img.freepik.com/fotos-kostenlos/elektrische-warnzeichen_1194-7007.jpg?t=st=1736871008~exp=1736874608~hmac=3deafee34196827190cfc1b2cb3721d7a307082625a552ffbb388e0111023e56&w=996"  
        url: "http://192.168.1.45"
        target: "_blank"

  - name: "Media"
    icon: "fa-solid fa-circle-play"
    items:
      - name: "Jellyfin"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png"
        #subtitle: "Another application"
        tag: "Media"
        url: "http://192.168.1.101:8096"
        target: "_blank"
      - name: "Jellyseerr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyseerr.png"
        url: "http://192.168.1.101:5055/" 
        tag: "request"
        target: "_blank"
      - name: "Synology"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/synology.png"
        tag: "NAS"
        url: "http://192.168.1.101"
        target: "_blank"
      - name: "bithumen"
        logo: "https://bhstatic.imageservecdn.com/img/locked.gif"
        tag: "torrent"
        url: "https://www.bithumen.be/"
        target: "_blank"
      - name: "IMDb"
        url: "https://www.imdb.com/"
        logo: "https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/171_Imdb_logo_logos-512.png"
        target: "_blank"
      - name: "TMDB"
        url: "https://www.themoviedb.org//"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/tmdb.png"
        target: "_blank"

  - name: "Servarr"
    icon: "fa-solid fa-cloud-arrow-down"
    items:
      - name: "Prowlarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png"
        url: "http://192.168.1.101:9696/" 
        tag: "indexer"
        target: "_blank"
      - name: "Radarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png"
        url: "http://192.168.1.101:7878/" 
        tag: "film"
        target: "_blank"
      - name: "Sonarr"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png"
        tag: "sorozat" 
        url: "http://192.168.1.101:8989/"
        target: "_blank"
      - name: "qBittorrent"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qbittorrent.png"
        url: "http://192.168.1.101:7777/" 
        tag: "torrent"
        target: "_blank"
      - name: "SABnzbd"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sabnzbd.png"
        url: "http://192.168.1.101:8080"
        type: "SABnzbd"
        apikey: "a04889ca142f4ffcb21d15dd50ca668a"
        downloadInterval: 5000
        tag: "nzb"
        target: "_blank"

  - name: "Google"
    icon: "fa-brands fa-google"
    items:
      - name: "Gmail"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/gmail.png"
        url: "https://mail.google.com/"
        target: "_blank"
      - name: "Kalender"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/google-calendar.png"
        url: "https://calendar.google.com/"
        target: "_blank"
      - name: "YouTube"
        url: "https://youtube.com"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/youtube.png"
        target: "_blank"
